### ISSUE TITLE
Question about release process

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1053]
Hi @da2ce7, following the [release process](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#9-create-comment-that-bumps-next-development-version) what should be the next develop version after [v3.0.0-rc.1](https://github.com/torrust/torrust-tracker/releases/tag/v3.0.0-rc.1)? `v3.0.1`, `v3.1.0`?

**Comment by da2ce7** [comment]
We create a v3 branch, that will be for bug fixes and new features. We bump the version based upon https://semver.org policy.

If we make a breaking change or start working on the next major version, then we can start using the develop branch again. This time with the v4.0.0-alpha... versioning.

In summary: (my recommendation)

Use the v3 branch while we work improving the v3.x.y series... once we decide to move onto the next major version: we move back to using the develop branch.

**Comment by josecelano** [comment]
> We create a v3 branch, that will be for bug fixes and new features. We bump the version based upon https://semver.org policy.
> 
> If we make a breaking change or start working on the next major version, then we can start using the develop branch again. This time with the v4.0.0-alpha... versioning.
> 
> In summary: (my recommendation)
> 
> Use the v3 branch while we work improving the v3.x.y series... once we decide to move onto the next major version: we move back to using the develop branch.

Hi @da2ce7, OK, then I will follow the release process only until [step 7](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#7-create-release-on-github-from-tag), and create a new v3 branch.

cc @mario-nt

**Comment by josecelano** [comment]
Hi @da2ce7, we have already merged into develop this PR:

https://github.com/torrust/torrust-tracker/pull/1058

and the cargo version is `version = "3.0.0-develop"`.

It should have been merged into branch `v3`, right?
