### ISSUE TITLE
[proposal] Move Torrust-Tracker to Apache License 2.0 to Match Aquatic Tracker

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-tracker#106]
Hello @WarmBeer,

I would like to propose that we change the license of this repository (Torrust Tracker) to the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.html).

My primary motivation for promoting this change is to have bi-directional license comparably with the [aquatic: high-performance open BitTorrent tracker](https://github.com/greatest-ape/aquatic).

Currently our license permits us to take code from aquatic's repository, however, we are not able to return the favor of allowing our code to be copied by @greatest-ape.

It should be noted that we in-fact already depend on some of aquatic's code by using the crate: [UDP BitTorrent tracker protocol](https://github.com/greatest-ape/aquatic/tree/master/aquatic_udp_protocol) to support our udp tracker implementation.

Other Contributors:  @naim94a @Power2All @josecelano @da2ce7 @pataquets @Aimless321 @ftsimas @makefu
In-Copy @cgbosse

---

_Question: Are there any real benefits for using the AGPL for Torrust-Tracker?_

_Question: Do you support the idea of moving Torrust Tracker to the "[Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.html)" and are also happy to change the license of your contributions in support ?_

**Comment by mickvandijke** [comment]
Hey @da2ce7 ,

I fully support switching to either Apache 2.0 or MIT. Distributing binaries would be a lot easier without having to work out all the incompatible licenses with AGPL :). I think it would also be more inviting for other developers and companies to build upon Torrust if we had a less restrictive license.
