### ISSUE TITLE
Extract package `torrust-tracker-client`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#1078]
Relates to:
  - https://github.com/torrust/torrust-tracker/issues/1067
  - https://github.com/torrust/torrust-tracker/issues/1067#issuecomment-2452249006

I have recently extracted a package [tracker-client](https://github.com/torrust/torrust-tracker/tree/develop/packages/tracker-client). This package contains all related to tracker clients with two functionalities:

- Low-level tracker clients (UDP and HTTP). This is a library.
- High-level tracker console clients (UDP, HTTP and Checker). These are console apps.

In our weekly meeting, we discussed it, and we decided to split this package into two packages too:

- `bittorrent-tracker-client`
- `torrust-tracker-client`

The reason is `bittorrent-tracker-client` are generic clients, and `torrust-tracker-client` is a Torrust console app.

### `packages/tracker-client`

- Crate: `bittorrent-tracker-client`
- It contains only a library with low-level clients.

### `console/tracker-client`

- Crate: `torrust-tracker-client`
- It contains the high-level console clients only.

**NOTICE**: [This console clients will be merged in the future in a single one](https://github.com/torrust/torrust-tracker/discussions/660).

cc @da2ce7

**Comment by da2ce7** [comment]
@josecelano  what do you think about using the `/tools/` instead of `/console/` for the client?

**Comment by josecelano** [comment]
> @josecelano what do you think about using the `/tools/` instead of `/console/` for the client?

Hi @da2ce7 I would use `console` until we have more `tools`, unless you already know about other tools we would like to implement. Since the crate name is different, we can change it later.

Alternatively, we could use `tools/console/tracker-client` if you think `console` is too specific to be in the root folder.
