### ISSUE TITLE
Replace `warp` with `axum`

### ISSUE THREAD

**Issue by mickvandijke** [torrust/torrust-tracker#116]
- [x] https://github.com/torrust/torrust-tracker/issues/143
- [x] https://github.com/torrust/torrust-tracker/issues/160

**Comment by da2ce7** [comment]
@josecelano suggested that we might want to consider [Rocket](https://rocket.rs/). From the looks of it, it seems really cool!

https://github.com/SergioBenitez/Rocket/tree/master

**Comment by da2ce7** [comment]
In addition, by the same primary author as Rocket, there is [Figment](https://github.com/SergioBenitez/Figment), for managing the configuration the application.

**Comment by mickvandijke** [comment]
> @josecelano suggested that we might want to consider [Rocket](https://rocket.rs/). From the looks of it, it seems really cool!
> 
> https://github.com/SergioBenitez/Rocket/tree/master

Hey @da2ce7 @josecelano ,

Rocket's documentation does look really nice, but the project still has a long way to go to compete with other webserver frameworks in Rust in terms of performance: https://web-frameworks-benchmark.netlify.app/result?asc=0&l=rust&metric=totalRequestsPerS&order_by=level512.

**Comment by da2ce7** [comment]
> > @josecelano suggested that we might want to consider [Rocket](https://rocket.rs/). From the looks of it, it seems really cool!
> > https://github.com/SergioBenitez/Rocket/tree/master
> 
> Hey @da2ce7 @josecelano ,
> 
> Rocket's documentation does look really nice, but the project still has a long way to go to compete with other webserver frameworks in Rust in terms of performance: https://web-frameworks-benchmark.netlify.app/result?asc=0&l=rust&metric=totalRequestsPerS&order_by=level512.

The difference seems to be about 50% of the speed of the competition. - This isn't so devastating.  Using a better and more correct interface is of significant advantage. Optimization for speed can always be preformed later.

**Comment by Power2All** [comment]
> > > @josecelano suggested that we might want to consider [Rocket](https://rocket.rs/). From the looks of it, it seems really cool!
> > > https://github.com/SergioBenitez/Rocket/tree/master
> > 
> > 
> > Hey @da2ce7 @josecelano ,
> > Rocket's documentation does look really nice, but the project still has a long way to go to compete with other webserver frameworks in Rust in terms of performance: https://web-frameworks-benchmark.netlify.app/result?asc=0&l=rust&metric=totalRequestsPerS&order_by=level512.
> 
> The difference seems to be about 50% of the speed of the competition. - This isn't so devastating. Using a better and more correct interface is of significant advantage. Optimization for speed can always be preformed later.

Sadly, performance is the crux when it comes to trackers.
Currently, I've got my own project based on Torrust-Tracker, and it's already straining with using Axum, let stand using Rocket where I could literally keelhaul my server.

**Comment by josecelano** [comment]
[Done](https://github.com/torrust/torrust-tracker/issues/160).
