### ISSUE TITLE
HTTP tracker over reverse proxy

### ISSUE THREAD

**Issue by redrocket3** [torrust/torrust-tracker#12]
I'm having troubles using the HTTP tracker over a reverse proxy if it is possible? I'm using caddy to reverse proxy the port assigned to the `http_tracker` section but upon creating a torrent and trying to connect two clients it does not download. I'm able to navigate to the domain I set in the proxy and it connects to the http tracker.

As a test I tried creating a torrent using the IP:PORT such as `http://1.1.1.1:6969/announce` and I was able to get two clients to share data but not through the reverse proxy.

Do you know what may be happening?

```
log_level = "info"
mode = "public"
db_path = "data.db"
cleanup_interval = 600
external_ip = "PUBLIC_SERVER_IP"

[udp_tracker]
bind_address = "0.0.0.0:6969"
announce_interval = 120

[http_tracker]
enabled = true
bind_address = "0.0.0.0:6969"
announce_interval = 120
ssl_enabled = false
ssl_cert_path = ""
ssl_key_path = ""
```

**Comment by mickvandijke** [comment]
Setting up Torrust behind a reverse proxy is not supported yet. I'll put this on top of the todo-list

**Comment by mickvandijke** [comment]
Implemented: https://github.com/torrust/torrust-tracker/commit/b8501f4da6a0aefdc48b68481c2672d4320656ea

[http_tracker]
...
on_reverse_proxy = true
