### ISSUE TITLE
API overhaul

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#141]
This issue is only to track the subtasks for the API overhaul.

- [x] https://github.com/torrust/torrust-tracker/issues/142
- [x] https://github.com/torrust/torrust-tracker/issues/143
- [x] https://github.com/torrust/torrust-tracker/issues/157
- [x] https://github.com/torrust/torrust-tracker/issues/238

Discarded:

- https://github.com/torrust/torrust-tracker/issues/144 (planned for API version 2)

From: https://github.com/torrust/torrust-tracker/pull/133#issuecomment-1362873425

**Comment by da2ce7** [comment]
Add the /v1/ to all the api endpoints.

**Comment by josecelano** [comment]
> Add the /v1/ to all the api endpoints.

Hye @da2ce7 I have included that change in the last issue https://github.com/torrust/torrust-tracker/issues/144

**Comment by josecelano** [comment]
> > Add the /v1/ to all the api endpoints.
> 
> Hye @da2ce7 I have included that change in the last issue #144

Hi @da2ce7, finally introducing the API prefix has its own issue:

https://github.com/torrust/torrust-tracker/issues/238

because the plan is to release a new major version with that change but before the whole API overhaul.

**Comment by josecelano** [comment]
The breaking changes are postponed until [version 2](https://github.com/torrust/torrust-tracker/issues/144).
