### ISSUE TITLE
Webtorrent support

### ISSUE THREAD

**Issue by Zorlin** [torrust/torrust-tracker#15]
It would be crazy cool if like Aquatic this supported webtorrent.

**Comment by Power2All** [comment]
@WarmBeer Can be closed, it's a protocol that is already supported by Torrust-Tracker.
WebTorrent is a protocol for "clients" in JavaScript for example, but does still announce and scrape a torrent server using HTTP/HTTPS, but I'm unsure if UDP is supported anyhow.
