### ISSUE TITLE
A database should be optional

### ISSUE THREAD

**Issue by mickvandijke** [torrust/torrust-tracker#151]
The tracker only needs a database if it wants to persist torrent statistics and private tracker keys between reboots. In all other cases a database should not be necessary.

**Comment by josecelano** [comment]
Hi @WarmBeer, the tracker can persist:

- Authentication keys for the HTTP tracker
- Torrents that are whitelisted
- Number of completed peers (seeders) for each torrent. That's what you call "torrent statistics", don't you?

Right now, the database is mandatory, but you can switch off "statistics persistence" with the core config option: `persistent_torrent_completed_stat`, right?

Could you elaborate on how you think we should implement this issue?

I suppose you want to have an extra config option to totally disable the database or maybe one independent flag for each feature?:

- `persistent_whitelist`
- `persistent_http_auth_keys`
- `persistent_torrent_completed_stat`

**Comment by mickvandijke** [comment]
Hi @josecelano ,

> Hi @WarmBeer, the tracker can persist:
> 
> * Authentication keys for the HTTP tracker
> * Torrents that are whitelisted
> * Number of completed peers (seeders) for each torrent. That's what you call "torrent statistics", don't you?
> 
> Right now, the database is mandatory, but you can switch off "statistics persistence" with the core config option: `persistent_torrent_completed_stat`, right?

Correct.

> Could you elaborate on how you think we should implement this issue?
> 
> I suppose you want to have an extra config option to totally disable the database or maybe one independent flag for each feature?:
> 
> * `persistent_whitelist`
> * `persistent_http_auth_keys`
> * `persistent_torrent_completed_stat`

Yes I think an independent flag for each feature would be nice. We could add a ‘[persistency]’ section to the config options with these three flags. And I suppose that the database url config option could also move to this section.

**Comment by josecelano** [comment]
Making the database optional would allow running the tracker without depending on the file system. We could:

- Not use the database file (`data.db`) required for SQLite.
- Not use the config file (`config.toml`). Use the env var instead. This is already possible.

With no file system dependency, we could run more straightforward docker commands to run a tracker using the docker. Instead of running:

```s
export TORRUST_TRACKER_USER_UID=1000 \
  && docker run -it \
    --user="$TORRUST_TRACKER_USER_UID" \
    --publish 6969:6969/udp \
    --publish 7070:7070/tcp \
    --publish 1212:1212/tcp \
    --volume "$(pwd)/storage":"/app/storage" \
    --volume "$(pwd)/config.toml":"/app/config.toml":ro \
    torrust/tracker:3.0.0-alpha.3
```


We could run:

```s
export TORRUST_TRACKER_USER_UID=1000 \
  && docker run -it \
    --user="$TORRUST_TRACKER_USER_UID" \
    --publish 6969:6969/udp \
    --publish 7070:7070/tcp \
    --publish 1212:1212/tcp \
    torrust/tracker:3.0.0-alpha.3
```

Without mounting any volume.

See https://github.com/torrust/torrust-tracker/pull/367

**Comment by josecelano** [comment]
I'm going to close this issue @WarmBeer. I think it's only a reminder that we should not make the database mandatory unless you are using a feature that requires persistence.

**Comment by josecelano** [comment]
@WarmBeer if you want, we can create an ADR like [this](https://github.com/torrust/torrust-index/tree/develop/docs/adrs) as a reminder that we would prefer the core tracker not to use persistence or allow running it without persistence (if you do not enable a feature that requires persistence).
