### ISSUE TITLE
Normalize module names containing multiple objects

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#155]
Sometimes single-file and folder module names containing more than one public struct are singular and sometimes plural.

For example:

- `src/http/request.rs` contains more than one request type.
- `src/http/response.rs` contains more than one response type.

In general, the plural is the most used option.

The folder name in the plural is better because it contains a collection of that "thing", but sometimes, when you use the namespace, the singular is easier to read, for example:

- `request::Announce` instead of `requests::Announce`.

Another advantage of the plural is you do not get Clippy warnings when a function in the module has a suffix which is the mod name, For example, mod `handlers` and an `xxx_handler` function inside.

I prefer the plural.

**Comment by josecelano** [comment]
We can create [ADRs](https://github.com/torrust/torrust-index/tree/develop/docs/adrs) like in the [Index](https://github.com/torrust/torrust-index/tree/develop/docs/adrs). And we can start changing it progressively.

**Comment by mickvandijke** [comment]
Hmm, I dislike using plurals in module names. But when I looked what the Rust std crate uses for the naming convention of modules, I saw that they use a plural name for the `std::collections` module that includes `HashMap`, `HashSet` etc.. So I suppose we should just follow the same plural convention as `std` then.
