### ISSUE TITLE
tracker error on one torrent, unsure of cause

### ISSUE THREAD

**Issue by jamiew0w** [torrust/torrust-tracker#17]
Here's the error when it announces:

```
thread 'tokio-runtime-worker' panicked at 'byte index 40 is not a char boundary; it is inside '�' (bytes 39..42) of `-lt0D80-�����������`', src/tracker.rs:77:23
```

There aren't any special characters in the name of the torrent and the passkey is definitely correct.

Let me know if there's anything else you might need!

**Comment by WarmBeer** [comment]
Seems to do with the peer_id again. I'm looking into it 👁️

**Comment by jamiew0w** [comment]
> Seems to do with the peer_id again. I'm looking into it 👁️

Actually @WarmBeer i think this is a case of user-error on my end. I just downloaded the torrent again fresh and it's working fine. I think I mislabelled it and never got around to checking up on it. It's announcing just fine now. Sorry for wasting your time.

**Comment by WarmBeer** [comment]
An error like this means that there is a condition that isn't handled properly in the code, so I will still have to fix it 👁️

**Comment by WarmBeer** [comment]
https://github.com/torrust/torrust-tracker/commit/e9e992fe11d0902047288b67b37c71b421aa89be
