### ISSUE TITLE
Isolate configuration and primitives in their own crates

### ISSUE THREAD

**Issue by mickvandijke** [torrust/torrust-tracker#173]
This has the benefit that we can import both into other projects. 

For example, I'm working on a [test-helpers crate](https://github.com/torrust/torrust-tracker/pull/170). And from this crate I want to use the tracker `Configuration`. 

In the current state, this is impossible. Because if we want to use the `Configuration` struct, we would have to import it from the `torrust-tracker` crate. So we would have to add the `torrust-tracker` crate to the dependencies of the `test-helpers` crate and that would mean that we have a cyclic dependency (`test-helpers` <-> `torrust-tracker`). Not good!

To avoid this and similar issues, we must isolate code in their own crates as much as possible. This way we can easily selectively import code without running into a cyclic disaster.

**Comment by josecelano** [comment]
@WarmBeer I think it's a good idea. And I think maybe we could use even more than one crate. In the future, we could have these crates:

- Common logic for trackers
- UDP tracker
- HTTP tracker
- This repo could be a kind of glue, a tracker "framework"

Regarding configuration, I would move the specific configuration for each service (`HttpTracker`, `UdpTracker`, etcetera) to its own module.

**Comment by josecelano** [comment]
Done by https://github.com/torrust/torrust-tracker/pull/226
