### ISSUE TITLE
Working on a forked version, with possible merge features

### ISSUE THREAD

**Issue by Power2All** [torrust/torrust-tracker#18]
Hi !

I just picked up your project, after my own GOLANG torrent tracker project hit a brick wall (literally), which was the Garbage Collector. Currently I am using your tracker software, but noticed a lot of flaws and possible huge improvements, using my own project as blue-print.

Some of the features I'm working on, and have already fixed:

* [X] Can now both separately listen on both HTTP and UDP on a IPv4 and IPv6 address
* [x] Persistent saving torrent hashes and completed into SQLite3
* [x] Persistent loading torrent hashes and completed from SQLite3
* [x] Statistics page using the API in JSON format and XML, this also to be "kind of" compatible with how OpenTracker (C/C++ project) shows their statistics
* [x] Adding a option to instead use X-Forwarded-For, also to look for CF-Connecting-IP
* [x] Changing the above CF-Connecting-IP into a dynamic string name
* [x] When using X-Forwarded-For, using a IP Proxy whitelist, so that the real remote address is picked up, since when you go through multiple proxy servers, they are all merged in a single string in the header
* [X] Improve the memory usage by saving the uint32 into a byte array, but only use that is needed minimum at most, thus each torrent hash in the memory will use up almost no memory.

I'm currently working on this on my own gitea server, but I could offer later a simple merge to your repository here.
Most of the fixes above, are personal preferences, and optional. Also, some small security improvements and memory usage optimizations :)
Oh right, and it shouldn't be breaking your current indexer project, as it's just purely internal improvements.

Currently running with some of the improvements:
![image](https://user-images.githubusercontent.com/2010549/158037479-76ec2ddb-17b9-4213-a700-030ce36d45b5.png)

**Comment by mickvandijke** [comment]
Hey @Power2All , that is awesome! I'm glad to see other people going through the code as there are indeed lots of improvements to be made and lots of features to add!

I saw on your account that your are Dutch too. Would you like to have a chat about Torrust so that we could potentially work together? If so, hit me up on Discord: `Warm beer#3352`

**Comment by Power2All** [comment]
Sure.
I tried adding you, but didn't work.
Try adding me with this: ``Power2All#1482``

**Comment by Power2All** [comment]
I've need potential help with something I cannot figure out.
NewTrackOn checks on basis of everything, but without a downloaded and uploaded query, so I'm trying to figure out how to make it so that it doesn't give a error when it's missing on a downloaded and uploaded query parameters in announce requests.
If you could tell me a simple solution for that, it would be nice, since I tried some stuff of RUST WARP but I couldn't get anything working. That's the only reason why NewTrackOn doesn't recognize the TCP and UDP to be working.
Also, the errors to the announce URL should be given in a Bencoded form for clients to read, since BitTorrent clients don't know what to do with json data returned ;)

Right now, I am adding MySQL support for loading and saving torrent hashes with completes as optional option.

**Comment by mickvandijke** [comment]
I've just sent you a friend request on Discord.
