### ISSUE TITLE
Release: `v3.0.0-alpha.1`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#248]
- [x] Publish the Github release
- [x] Publish crate on [crates.io](https://crates.io/)

**Comment by josecelano** [comment]
Hi @WarmBeer, I get an error trying to publish the crate.

I have to find out how to fix [this error](https://github.com/josecelano/torrust-tracker/actions/runs/4450248454/jobs/7815562925#step:4:11):

```
Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `torrust-tracker-configuration` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
Error: Process completed with exit code [10](https://github.com/josecelano/torrust-tracker/actions/runs/4450248454/jobs/7815562925#step:4:11)1.
```

I assume that the command `cargo publish` should publish 5 crates with the same version: `3.0.0-alpha.1`.

You can reproduce the error locally with:

```
$ cargo publish --dry-run
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `torrust-tracker-configuration` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```

**Comment by josecelano** [comment]
It seems it's not possible to publish all of them at the same time with just `cargo publish`:


- https://stackoverflow.com/a/72350612/3012842
- https://github.com/rust-lang/cargo/issues/1169
- https://www.reddit.com/r/rust/comments/a39er8/how_do_you_publish_your_cargo_workspace_packages/

**Comment by josecelano** [comment]
Hi @da2ce7 @WarmBeer, we have to review the release process. This is what we have now:

- `main` and `develop` branches.
- `main` branch has some protection rules. For example, it requires a review before merging.
- We publish the new crate version with a workflow in a fork. The workflow is triggered for tags starting with the `v` prefix. That means anyone can create tags and run the workflows to publish the crates but the workflow only works if you have the crates.io token.

The problem is that we cannot guarantee that all tags have been published as a crate.

We could add a tag protection rule to restrict the creation of version tags.

**Comment by josecelano** [comment]
The workflow has published two out of 5 packages:

Workflow: https://github.com/josecelano/torrust-tracker/actions/runs/4450910142/jobs/7817035784

- https://crates.io/crates/torrust-tracker-located-error
- https://crates.io/crates/torrust-tracker-primitives

I get the same error on the third :-/

By the way, we need to add a README to the new packages.

**Comment by josecelano** [comment]
The error was fixed by adding the concrete version to the workspace packages:

https://github.com/torrust/torrust-tracker/commit/354edec3cd17ce721fd5aa07a91abab86fbaf2e2

```
torrust-tracker-primitives = { version = "3.0.0-alpha.1", path = "packages/primitives" }
torrust-tracker-configuration = { version = "3.0.0-alpha.1", path = "packages/configuration" }
torrust-tracker-located-error = { version = "3.0.0-alpha.1", path = "packages/located-error" }
torrust-tracker-test-helpers = { version = "3.0.0-alpha.1", path = "packages/test-helpers" }
```

I'm using the same version for all workspace packages. It is the recommended way. I guess we can do that until we extract them into independent repos.

When you build the app locally, I assume you get the latest build from the workspace package even if you specify the version because the version is inherited from the parent workspace.

**Comment by josecelano** [comment]
`v3.0.0-alpha.1` crates:

- https://crates.io/crates/torrust-tracker
- https://crates.io/crates/torrust-tracker-configuration
- https://crates.io/crates/torrust-tracker-located-error
- https://crates.io/crates/torrust-tracker-primitives
- https://crates.io/crates/torrust-tracker-test-helpers

**Comment by josecelano** [comment]
Hey @da2ce7 send me your crates.io username so that I can add you as owner.

**Comment by da2ce7** [comment]
@josecelano My username seems to be "da2ce7" as it is linked to my github account.
