### ISSUE TITLE
`MAX_SCRAPE_TORRENTS` (74) limit applied to returned peer list in announce request?

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#262]
There is a `MAX_SCRAPE_TORRENTS` constant declared [here](https://github.com/torrust/torrust-tracker/blob/develop/src/shared/bit_torrent/common.rs#L4).

The [BEP 15. UDP Tracker Protocol for `BitTorrent`](https://www.bittorrent.org/beps/bep_0015.html)
defines this limit:

"Up to about 74 torrents can be scraped at once. A full scrape can't be done with this protocol."

The [BEP 48. Tracker Protocol Extension: Scrape](https://www.bittorrent.org/beps/bep_0048.html)
does not explicitly mention this limit, but the limit is being used for
both the UDP and HTTP trackers since it's applied at the domain level:

- [Here](https://github.com/torrust/torrust-tracker/blob/develop/src/tracker/torrent.rs#L129)
- And [here](https://github.com/torrust/torrust-tracker/blob/develop/src/tracker/torrent.rs#L129) for limiting the number of peers in the `announce` response.

@WarmBeer is this limit defined in any BEP or just a Torrust Tracker limit?

I would use a different const for the peer list limit. It's confusing.

**Comment by josecelano** [comment]
It seems the tracker is also ignoring the `num_want` param in the announce request.

`num_want` is the number of peers the client wants in the `announce` response (peer list).

See https://www.bittorrent.org/beps/bep_0015.html

Right now:

- We always return less than 74
- We ignore the `num_want`

**Comment by josecelano** [comment]
Hey, @WarmBeer could you take a look at this issue?

**Comment by mickvandijke** [comment]
> There is a `MAX_SCRAPE_TORRENTS` constant declared [here](https://github.com/torrust/torrust-tracker/blob/develop/src/shared/bit_torrent/common.rs#L4).
> 
> The [BEP 15. UDP Tracker Protocol for `BitTorrent`](https://www.bittorrent.org/beps/bep_0015.html) defines this limit:
> 
> "Up to about 74 torrents can be scraped at once. A full scrape can't be done with this protocol."
> 
> The [BEP 48. Tracker Protocol Extension: Scrape](https://www.bittorrent.org/beps/bep_0048.html) does not explicitly mention this limit, but the limit is being used for both the UDP and HTTP trackers since it's applied at the domain level:
> 
>     * [Here](https://github.com/torrust/torrust-tracker/blob/develop/src/tracker/torrent.rs#L129)
> 
>     * And [here](https://github.com/torrust/torrust-tracker/blob/develop/src/tracker/torrent.rs#L129) for limiting the number of peers in the `announce` response.
> 
> 
> @WarmBeer is this limit defined in any BEP or just a Torrust Tracker limit?
> 
> I would use a different const for the peer list limit. It's confusing.

The 74 torrent limit during for a scrape response is indeed just a UDP limitation and should not necessarily be applied to HTTP.

However, trackers can hold millions of torrents. If we dump all that torrent info into a single HTTP scrape response, the tracker might have some large memory spikes. 

It would be around 32 bytes per torrent. If a tracker holds 50,000,000 torrents, the scrape response would be 1.6 gigabytes. Not too bad maybe.

Should we leave the HTTP scrape response limitless?

CC @josecelano @da2ce7

**Comment by josecelano** [comment]
> > There is a `MAX_SCRAPE_TORRENTS` constant declared [here](https://github.com/torrust/torrust-tracker/blob/develop/src/shared/bit_torrent/common.rs#L4).
> > 
> > The [BEP 15. UDP Tracker Protocol for `BitTorrent`](https://www.bittorrent.org/beps/bep_0015.html) defines this limit:
> > 
> > "Up to about 74 torrents can be scraped at once. A full scrape can't be done with this protocol."
> > 
> > The [BEP 48. Tracker Protocol Extension: Scrape](https://www.bittorrent.org/beps/bep_0048.html) does not explicitly mention this limit, but the limit is being used for both the UDP and HTTP trackers since it's applied at the domain level:
> > 
> >     * [Here](https://github.com/torrust/torrust-tracker/blob/develop/src/tracker/torrent.rs#L129)
> > 
> >     * And [here](https://github.com/torrust/torrust-tracker/blob/develop/src/tracker/torrent.rs#L129) for limiting the number of peers in the `announce` response.
> > 
> > 
> > @WarmBeer is this limit defined in any BEP or just a Torrust Tracker limit?
> > 
> > I would use a different const for the peer list limit. It's confusing.
> 
> The 74 torrent limit during for a scrape response is indeed just a UDP limitation and should not necessarily be applied to HTTP.
> 
> However, trackers can hold millions of torrents. If we dump all that torrent info into a single HTTP scrape response, the tracker might have some large memory spikes. 
> 
> It would be around 32 bytes per torrent. If a tracker holds 50,000,000 torrents, the scrape response would be 1.6 gigabytes. Not too bad maybe.
> 
> Should we leave the HTTP scrape response limitless?
> 
> CC @josecelano @da2ce7 
> 

Hi @WarmBeer I'm ok with the limit for both trackers in the **scrape** response, but notice we are also limiting the peer list in the **announce** response. I'm also Ok with this limit. My proposal is not to remove the limit but use three different constants or maybe use  configuration settings for the ones not defined in BEPs. But in any case use different names for the three of them.

**Comment by mickvandijke** [comment]
> > > There is a `MAX_SCRAPE_TORRENTS` constant declared [here](https://github.com/torrust/torrust-tracker/blob/develop/src/shared/bit_torrent/common.rs#L4).
> > > The [BEP 15. UDP Tracker Protocol for `BitTorrent`](https://www.bittorrent.org/beps/bep_0015.html) defines this limit:
> > > "Up to about 74 torrents can be scraped at once. A full scrape can't be done with this protocol."
> > > The [BEP 48. Tracker Protocol Extension: Scrape](https://www.bittorrent.org/beps/bep_0048.html) does not explicitly mention this limit, but the limit is being used for both the UDP and HTTP trackers since it's applied at the domain level:
> > > ```
> > > * [Here](https://github.com/torrust/torrust-tracker/blob/develop/src/tracker/torrent.rs#L129)
> > > 
> > > * And [here](https://github.com/torrust/torrust-tracker/blob/develop/src/tracker/torrent.rs#L129) for limiting the number of peers in the `announce` response.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @WarmBeer is this limit defined in any BEP or just a Torrust Tracker limit?
> > > I would use a different const for the peer list limit. It's confusing.
> > 
> > 
> > The 74 torrent limit during for a scrape response is indeed just a UDP limitation and should not necessarily be applied to HTTP.
> > However, trackers can hold millions of torrents. If we dump all that torrent info into a single HTTP scrape response, the tracker might have some large memory spikes.
> > It would be around 32 bytes per torrent. If a tracker holds 50,000,000 torrents, the scrape response would be 1.6 gigabytes. Not too bad maybe.
> > Should we leave the HTTP scrape response limitless?
> > CC @josecelano @da2ce7
> 
> Hi @WarmBeer I'm ok with the limit for both trackers in the **scrape** response, but notice we are also limiting the peer list in the **announce** response. I'm also Ok with this limit. My proposal is not to remove the limit but use three different constants or maybe use configuration settings for the ones not defined in BEPs. But in any case use different names for the three of them.

Ok, I will refactor it.
