### ISSUE TITLE
Remove BEP-41 support from docs

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#272]
Hi @WarmBeer, The README states the tracker implements the [BEP 41. UDP Tracker Protocol Extensions](https://www.bittorrent.org/beps/bep_0041.html).

As far as I know, we are using [aquatic_udp_protocol](https://github.com/greatest-ape/aquatic#aquatic_udp-udp-bittorrent-tracker), which, I think, does not support BEP41.

**Comment by mickvandijke** [comment]
Hey @josecelano , We indeed dropped support for BEP 41 when we switched to aquatic. The tracker used to support optional private keys through UDP.

**Comment by josecelano** [comment]
Done via https://github.com/torrust/torrust-tracker/commit/3c2ee42813ef2b0038e3f1f503108a3860a87db2
