### ISSUE TITLE
Add middleware to compress responses

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#326]
The HTTP tracker and the API do not send a compressed response.

[tower_http::compression](https://docs.rs/tower-http/0.4.0/tower_http/compression/index.html) middleware could be used.

### Links

- https://tokio.rs/blog/2021-07-announcing-axum#middleware

**Comment by alexohneander** [comment]
@josecelano Do we want to use this as default or do we want to enable/disable this via a config line?

**Comment by da2ce7** [comment]
Hello @alexohneander HTTP since the big-bang has supported compression, I sugest that we just blanket enable it for everything; it is a cheap and effective optimization.
