### ISSUE TITLE
Add Existing Tracker Key

### ISSUE THREAD

**Issue by iloveyourwife** [torrust/torrust-tracker#35]
Hi,
I can see in the documentation : https://torrust.com/torrust-tracker/api/#tracker-keys that we can generate or delete tracker keys.
But is it possible to add existing tracker keys ? I'm migrating from another famous tracker, and I want to keep my existing users tracker key from my database.
The keys are in similar format.

Thanks

**Comment by mickvandijke** [comment]
It is only possible to manually add existing tracker keys directly to the database and they have to be 32 chars.

**Comment by josecelano** [comment]
> Hi, I can see in the documentation : https://torrust.com/torrust-tracker/api/#tracker-keys that we can generate or delete tracker keys. But is it possible to add existing tracker keys ? I'm migrating from another famous tracker, and I want to keep my existing users tracker key from my database. The keys are in similar format.
> 
> Thanks

hi @iloveyourwife , I would like to know more about your case. It would be interesting to make migration from other tools more accessible. We've merged a new [feature to migrate data from a previous DB schema to the last one](https://github.com/torrust/torrust-index-backend/pull/77).

Maybe we can write a new console command to import keys, but we need to know the following:

- If keys are compatible. If they are not, how hard would it be to support both types?
- How difficult would it be to write a command for the importation
- If that's the only impediment for you to migrate

**Comment by josecelano** [comment]
I'm going to close it until we have more info.
