### ISSUE TITLE
Getting compiling errors

### ISSUE THREAD

**Issue by BabaBooey84** [torrust/torrust-tracker#40]
I'm trying to compile the torrust tracker on a fresh Ubuntu 20.04 VPS. Help :sweat_smile:

> Compiling torrust-tracker v2.1.2 (/opt/torrust/torrust-tracker)
error: could not compile `torrust-tracker`
Caused by:
  process didn't exit successfully: `rustc --crate-name torrust_tracker --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto=fat -C metadata=abe589342472d11d -C extra-filename=-abe589342472d11d --out-dir /opt/torrust/torrust-tracker/target/release/deps -L dependency=/opt/torrust/torrust-tracker/target/release/deps --extern aquatic_udp_protocol=/opt/torrust/torrust-tracker/target/release/deps/libaquatic_udp_protocol-256099ae6a911d5f.rlib --extern binascii=/opt/torrust/torrust-tracker/target/release/deps/libbinascii-9acfca8516b6a49b.rlib --extern byteorder=/opt/torrust/torrust-tracker/target/release/deps/libbyteorder-a702fa3de9d93cfd.rlib --extern chrono=/opt/torrust/torrust-tracker/target/release/deps/libchrono-010dffbe121777a9.rlib --extern config=/opt/torrust/torrust-tracker/target/release/deps/libconfig-099683e27e43327d.rlib --extern derive_more=/opt/torrust/torrust-tracker/target/release/deps/libderive_more-692afb38f795b77c.so --extern env_logger=/opt/torrust/torrust-tracker/target/release/deps/libenv_logger-c3fde9307b1bf67d.rlib --extern external_ip=/opt/torrust/torrust-tracker/target/release/deps/libexternal_ip-7a2196c7896b0ddc.rlib --extern fern=/opt/torrust/torrust-tracker/target/release/deps/libfern-d875b3da92fde325.rlib --extern hex=/opt/torrust/torrust-tracker/target/release/deps/libhex-698b34e1c9f6cfdc.rlib --extern log=/opt/torrust/torrust-tracker/target/release/deps/liblog-5cfdbebb2ffcf419.rlib --extern percent_encoding=/opt/torrust/torrust-tracker/target/release/deps/libpercent_encoding-7c21edb5ded068c3.rlib --extern r2d2=/opt/torrust/torrust-tracker/target/release/deps/libr2d2-78c16af48b279186.rlib --extern r2d2_sqlite=/opt/torrust/torrust-tracker/target/release/deps/libr2d2_sqlite-114e9752096032e8.rlib --extern rand=/opt/torrust/torrust-tracker/target/release/deps/librand-12f552a3a8bf93df.rlib --extern serde=/opt/torrust/torrust-tracker/target/release/deps/libserde-8a17fcae9b1387aa.rlib --extern serde_bencode=/opt/torrust/torrust-tracker/target/release/deps/libserde_bencode-f98c8dd0e18fa1f5.rlib --extern serde_bytes=/opt/torrust/torrust-tracker/target/release/deps/libserde_bytes-eb192722ce71a6b7.rlib --extern serde_json=/opt/torrust/torrust-tracker/target/release/deps/libserde_json-2937bc685dbbc7b2.rlib --extern thiserror=/opt/torrust/torrust-tracker/target/release/deps/libthiserror-ea1533eb85d848d9.rlib --extern tokio=/opt/torrust/torrust-tracker/target/release/deps/libtokio-e4f904d0b7baee09.rlib --extern toml=/opt/torrust/torrust-tracker/target/release/deps/libtoml-f6ae5c7bb1775a19.rlib --extern torrust_tracker=/opt/torrust/torrust-tracker/target/release/deps/libtorrust_tracker-76439efdbbd1d5ef.rlib --extern warp=/opt/torrust/torrust-tracker/target/release/deps/libwarp-9411289a13052a90.rlib -L native=/opt/torrust/torrust-tracker/target/release/build/ring-cce19ede844b507a/out` (signal: 9, SIGKILL: kill)

**Comment by josecelano** [comment]
Fixed [here](https://github.com/torrust/torrust-documentation/issues/1).
