### ISSUE TITLE
Peer and torrent specific statistics

### ISSUE THREAD

**Issue by AnimeSub** [torrust/torrust-tracker#48]
Statistics which will show how much has been transferred, how many people downloaded, how many people are downloading, graph, etc will look awesome

**Comment by babico** [comment]
I made a simple version, you can check it using these two links

to save this history: https://github.com/babico/torrust-tracker-json

this to plot graph using history (right click > "View Page Source Code" > js scripts are open): https://www.babico.name.tr/stats/
