### ISSUE TITLE
Option to disable auth key expiration

### ISSUE THREAD

**Issue by rakema01** [torrust/torrust-tracker#49]
Would be a neat thing to have when the focus of the site is to seed for long periods of time. Also especially helpful when you've got too many torrents and having to change the tracker URL to match the key is a pain. Of course, there's the option to change the expiry length to a random huge number but having an option to outright disable expiry checks is a bit cleaner in my opinion. In its place, we could have an option for the key be manually regenerated when needed.

**Comment by mickvandijke** [comment]
Good idea. I will make it so that if valid_until is set to 0, the key won't expire.
