### ISSUE TITLE
Optimize torrent/peers list reading and writing by breaking up the `tracker.torrents` field into smaller pieces

### ISSUE THREAD

**Issue by mickvandijke** [torrust/torrust-tracker#495]
We were talking about refactoring the torrents map in the `Tracker` struct to reduce the amount of write locks needed on the entire torrents map. This would theoretically improve torrent announce performance when you have a lot of torrents being updated at the same time.

Refactor:

`torrents: RwLock<std::collections::BTreeMap<InfoHash, torrent::Entry>>,`

To:

`torrents: RwLock<std::collections::BTreeMap<InfoHash, Arc<Mutex<torrent::Entry>>>>,`

**Comment by josecelano** [comment]
Hi @WarmBeer I would suggest taking a look at @Power2All's implementation [here](https://github.com/Power2All/torrust-actix/blob/master/src/tracker.rs) and also at [this discussion](https://github.com/torrust/torrust-tracker/discussions/329).

**Comment by mickvandijke** [comment]
Relevant discussion: https://github.com/torrust/torrust-tracker/discussions/504

**Comment by mickvandijke** [comment]
Superseded by https://github.com/torrust/torrust-tracker/issues/565
