### ISSUE TITLE
Project License is listed as AGPL 3.0 all other repositories have the Nautilus standard licensing approach.

### ISSUE THREAD

**Issue by cgbosse** [torrust/torrust-tracker#52]
Questions:
- Why is this repo's license setup different?
- Shall we customize all the organizations license to just name Torrust or shall we indicate its belonging to the Nautilus organization and leave the licenses as they are.

![image](https://user-images.githubusercontent.com/15330600/174796276-7d0430eb-de84-41d8-a93c-0eb8afdf4b96.png)

**Comment by mickvandijke** [comment]
1. This repository/project does not contain any UI elements such as images, that’s why it is only licensed as AGPL-3.0 while torrust-index is dual-licensed I guess.

2. Yes the licenses still need to be updated to point to Torrust.

**Comment by cgbosse** [comment]
I think that we should keep the same licensing approach here.
Folders and documents should be the same.

The license for code is AGPL either way.
Since it is clearly stated that the AGPL 3.0 license applies to code it is ok to follow the same approach as with the other repositories.

Besides there is now one image the logo. : )

I will create the Licensing folder and include the contributor agreement and other licenses either way.

**Comment by cgbosse** [comment]
I will prepare the merge and not merge until we discuss it tomorrow.

**Comment by cgbosse** [comment]
Was already addressed.
