### ISSUE TITLE
Change `announce_interval` and `min_announce_interval` to 5 minutes

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#535]
I'm setting up a live demo. I was trying to add the tracker to https://newtrackon.com/ but the request was rejected for the HTTPs tracker:

```json
{
  "complete": 1,
  "incomplete": 0,
  "interval": 120,
  "min interval": 120,
  "peers": [],
  "peers6": []
}
```

and UDP tracker:

```json
{
  "interval": 120, 
  "leechers": 0,
  "peers": [],
  "seeds": 1
}
```

For the same reason:

> Tracker rejected for having an interval shorter than 5 minutes or longer than 3 hours

Should we increase the `announce_interval` and  `min_announce_interval` up to 5 minutes? cc @da2ce7 @WarmBeer 

![image](https://github.com/torrust/torrust-tracker/assets/58816/e64747b6-f953-4fab-bc85-ec98f7cd98dd)

```rust
    /// Interval in seconds that the client should wait between sending regular
    /// announce requests to the tracker.
    ///
    /// It's a **recommended** wait time between announcements.
    ///
    /// This is the standard amount of time that clients should wait between
    /// sending consecutive announcements to the tracker. This value is set by
    /// the tracker and is typically provided in the tracker's response to a
    /// client's initial request. It serves as a guideline for clients to know
    /// how often they should contact the tracker for updates on the peer list,
    /// while ensuring that the tracker is not overwhelmed with requests.
    pub announce_interval: u32,
    /// Minimum announce interval. Clients must not reannounce more frequently
    /// than this.
    ///
    /// It establishes the shortest allowed wait time.
    ///
    /// This is an optional parameter in the protocol that the tracker may
    /// provide in its response. It sets a lower limit on the frequency at which
    /// clients are allowed to send announcements. Clients should respect this
    /// value to prevent sending too many requests in a short period, which
    /// could lead to excessive load on the tracker or even getting banned by
    /// the tracker for not adhering to the rules.
    pub min_announce_interval: u32,
```

**Comment by josecelano** [comment]
After updating only the `announce_interval = 300` the UDP tracker was accepted but the HTTP tracker was still rejected:

![image](https://github.com/torrust/torrust-tracker/assets/58816/35c817e5-8547-4ee6-845b-2fc96e32d014)

**Comment by mickvandijke** [comment]
> I'm setting up a live demo. I was trying to add the tracker to https://newtrackon.com/ but the request was rejected for the HTTPs tracker:
> 
> ```json
> {
>   "complete": 1,
>   "incomplete": 0,
>   "interval": 120,
>   "min interval": 120,
>   "peers": [],
>   "peers6": []
> }
> ```
> 
> and UDP tracker:
> 
> ```json
> {
>   "interval": 120, 
>   "leechers": 0,
>   "peers": [],
>   "seeds": 1
> }
> ```
> 
> For the same reason:
> 
> > Tracker rejected for having an interval shorter than 5 minutes or longer than 3 hours
> 
> Should we increase the `announce_interval` and `min_announce_interval` up to 5 minutes? cc @da2ce7 @WarmBeer
> 
> ![image](https://private-user-images.githubusercontent.com/58816/289527024-e64747b6-f953-4fab-bc85-ec98f7cd98dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTc0MTksIm5iZiI6MTcwMjI5NzExOSwicGF0aCI6Ii81ODgxNi8yODk1MjcwMjQtZTY0NzQ3YjYtZjk1My00ZmFiLWJjODUtZWM5OGY3Y2Q5OGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDEyMTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NDE1MWRhMTg0N2I5ZDEyOWM2MDE2NWM3ZWUyMmY0ZDhkOWI4YmIzM2MyYzViZWM4YTA0OWUxOTE4NmNiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A_IGo6kMdq-XwmzH8XpT27Kr1WBPKFBosJ9W5ajPmKg)
> 
> ```rust
>     /// Interval in seconds that the client should wait between sending regular
>     /// announce requests to the tracker.
>     ///
>     /// It's a **recommended** wait time between announcements.
>     ///
>     /// This is the standard amount of time that clients should wait between
>     /// sending consecutive announcements to the tracker. This value is set by
>     /// the tracker and is typically provided in the tracker's response to a
>     /// client's initial request. It serves as a guideline for clients to know
>     /// how often they should contact the tracker for updates on the peer list,
>     /// while ensuring that the tracker is not overwhelmed with requests.
>     pub announce_interval: u32,
>     /// Minimum announce interval. Clients must not reannounce more frequently
>     /// than this.
>     ///
>     /// It establishes the shortest allowed wait time.
>     ///
>     /// This is an optional parameter in the protocol that the tracker may
>     /// provide in its response. It sets a lower limit on the frequency at which
>     /// clients are allowed to send announcements. Clients should respect this
>     /// value to prevent sending too many requests in a short period, which
>     /// could lead to excessive load on the tracker or even getting banned by
>     /// the tracker for not adhering to the rules.
>     pub min_announce_interval: u32,
> ```

It doesn’t hurt to update the minimum announce interval on the demo I suppose. Odd that the usual interval of 120 seconds is not supported by newtrackon.

**Comment by josecelano** [comment]
Hi @WarmBeer we can leave the default value and just mention this case in the docs. [They explained why they do so](https://github.com/CorralPeltzer/newTrackon/issues/120).

**Comment by josecelano** [comment]
> Hi @WarmBeer we can leave the default value and just mention this case in the docs. [They explained why they do so](https://github.com/CorralPeltzer/newTrackon/issues/120).

I've changed my mind I think we do not need to include this case in our docs. This issue should be enough.
