### ISSUE TITLE
Use dashmap for torrent in memory storage instead of the std hashmap

### ISSUE THREAD

**Issue by mickvandijke** [torrust/torrust-tracker#565]
DashMap should be significantly faster in concurrent reads and writes compared to the std HashMap.

https://github.com/xacrimon/dashmap
https://github.com/xacrimon/conc-map-bench

**Comment by josecelano** [comment]
Relates to: https://github.com/torrust/torrust-tracker/issues/566

Hi @WarmBeer if you are going to reimplement this, maybe you could also consider trying to avoid [this problem](https://github.com/torrust/torrust-tracker/issues/566).

**Comment by josecelano** [comment]
Relates to: https://github.com/torrust/torrust-tracker/issues/646
