### ISSUE TITLE
Future, roadmap and releases for Torrust?

### ISSUE THREAD

**Issue by ghost** [torrust/torrust-tracker#577]
Hey Guys,
I have been following the project from afar for a while. Clearly a lot of work has been going into Torrust over the past few years, and I look forward to seeing what heights it'll manage to reach.
That said, I was wondering if you had an ETA or roadmap concerning the next full releases for the Torrust applications?
Multiple pre-releases aside, we're slowly inching closer to the two year mark since the last full release in this repo, and soon the same will also be applicable to the index and GUI.

**Comment by josecelano** [comment]
Hi @ty5e3a45, [this comment](https://github.com/torrust/torrust-index/discussions/93#discussioncomment-4862870) by @da2ce7 summarizes our current state.

We are still working on the release v3.0.0. for all repos. I do not know how long it will take us to finish it. It should be soon but sometimes we find new things we consider necessary to include in the release.

I've also deployed a [live demo](http://index.torrust-demo.com/) so people can contribute to testing it. The tracker is running on: https://tracker.torrust-demo.com and udp://tracker.torrust-demo.com:6969.

**Comment by josecelano** [comment]
Hi, @ty5e3a45 we have started working on the roadmap, but it is still WIP. See:

https://github.com/torrust/torrust-tracker/issues/633

For [missing features](https://github.com/torrust/torrust-tracker/discussions/categories/feature-requests), or questions about the [roadmap](https://github.com/torrust/torrust-tracker/discussions/632) you can use [discussions](https://github.com/torrust/torrust-tracker/discussions).
