### ISSUE TITLE
Re-Enable Rust-Stable CI for Rust 1.75+

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-tracker#580]
Now that [async-trait](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html) has been stabilized in [Rust 1.75.0](https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html), we can start using the stable paths in the ci again.

**Comment by josecelano** [comment]
Hi @da2ce7 in which workflows? I think the coverage workflow needs the nightly toolchain.

Do you mean the container images? because of [this commit](https://github.com/torrust/torrust-tracker/commit/b0a1bb03059250068d2f9edc3050420f3b78aeab):

```dockerfile
FROM rustlang/rust:nightly-bookworm as chef
```
