### ISSUE TITLE
E2E tests runner refactor. Use `clap` and `anyhow`

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#659]
I'm using `clap` and `anyhow` in all binaries because the configuration is getting more complex.

Allow to inject the tracker configuration with env vars.

Currently, you can run it like this:

```console
cargo run --bin e2e_tests_runner "./share/default/config/tracker.e2e.container.sqlite3.toml"
```

But it would be also interesting to run it with:

```console
TORRUST_TRACKER_CONFIG=[value] cargo run --bin e2e_tests_runner
```

or:

```console
TORRUST_TRACKER_PATH_CONFIG="./share/default/config/tracker.e2e.container.sqlite3.toml" cargo run --bin e2e_tests_runner
```

### Subtasks

- [x] Migrate to `clap` and `anyhow`.
- [x] Allow injecting config with env vars.

cc @da2ce7

**Comment by da2ce7** [comment]
@josecelano I'm supportive of generally moving to [clap](https://github.com/clap-rs/clap) and [anyhow](https://github.com/dtolnay/anyhow), for all of our projects.

**Comment by josecelano** [comment]
Finally, you can execute it with:

```bash
cargo run --bin e2e_tests_runner -- --config-toml-path "./share/default/config/tracker.e2e.container.sqlite3.toml"
```

Or:

```bash
TORRUST_TRACKER_CONFIG_TOML_PATH="./share/default/config/tracker.e2e.container.sqlite3.toml" cargo run --bin e2e_tests_runner
```

Or:

```bash
TORRUST_TRACKER_CONFIG_TOML=$(cat "./share/default/config/tracker.e2e.container.sqlite3.toml") cargo run --bin e2e_tests_runner
```
