### ISSUE TITLE
Compilation issues for --target `armv7-unknown-linux-gnueabihf`

### ISSUE THREAD

**Issue by mickvandijke** [torrust/torrust-tracker#68]
Torrust won't compile to armv7-unknown-linux-gnueabihf (Raspberry Pi etc..).

**Comment by mickvandijke** [comment]
After some painful hours, I've figured out a way to cross compile to armv7-unknown-linux-gnueabihf from an Ubuntu host.

I mostly ran into errors with openssl and sqlite3, so I had to add and update some dependencies in the Cargo.toml to fix these. `openssl` had to be included with the `vendored` feature:
```toml
openssl = { version = "0.10.41", features = ["vendored"] }
```

And `rusqlite` had to include the feature `bundled` through the `r2d2_sqlite` crate:
```toml
r2d2_sqlite = { version = "0.21.0", features = ["bundled"] }
```

These are the commands I had to use for the compiler to succeed:
```
sudo apt-get install binutils-arm-linux-gnueabihf gcc-arm-linux-gnueabihf musl-tools

sudo apt-get install gcc-multilib

sudo apt-get install clang

sudo apt-get install sudo apt-get install libsqlite3-dev openssl libssl-dev pkg-config

sudo apt-get install -y libc6-armhf-cross libc6-dev-armhf-cross

sudo ln -s /usr/bin/arm-linux-gnueabihf-gcc /usr/bin/arm-linux-musleabihf-gcc
```

If you are coss compiling to armv7, you also have to add the following to `torrust-tracker/.cargo/config`:
```
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
```
If this file and folder don’t exist, you’ll have to create them yourself.

**Comment by mickvandijke** [comment]
https://github.com/torrust/torrust-tracker/pull/69

**Comment by josecelano** [comment]
hi @WarmBeer in the docker configuration I'm working on [here](https://github.com/torrust/torrust-tracker/pull/123), I'm using a docker image that probably does that internally. It works with `--target x86_64-unknown-linux-musl` but it does not work with `--target armv7-unknown-linux-gnueabihf`.

I think we could add a GitHub workflow to test cross-compilations like [this](https://github.com/sfackler/rust-openssl/blob/master/.github/workflows/ci.yml).

We can start with only this case for the time being so we do not lose this information. I think it's very important to know the exact dependencies of the program to ensure it runs in as many systems as possible. This could be a pain if we keep adding more and more "hidden" or unexplicit indirect dependencies.

At least with the docker configuration, I'm working we know well the dependencies for one system.
