### ISSUE TITLE
Update `reqwest` dependency when it uses `hyper` v1

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#706]
Relates to: 

- https://github.com/seanmonstar/reqwest/issues/2039
- https://github.com/torrust/torrust-tracker/issues/510

**Comment by josecelano** [comment]
`request` was upgraded to use hyper v1 in the `0.12-dev` branch but there is no release yet.

The [issue](https://github.com/seanmonstar/reqwest/issues/2039) was reverted here: https://github.com/seanmonstar/reqwest/pull/2170

**Comment by da2ce7** [comment]
was completed in #745
