### ISSUE TITLE
Failed project build due to unused struct with rustc 1.78.0-nightly (a165f1f65 2024-03-12) 

### ISSUE THREAD

**Issue by mario-nt** [torrust/torrust-tracker#731]
When trying to compile the project with rustc 1.78.0-nightly (a165f1f65 2024-03-12) we get the following error :

![image](https://github.com/torrust/torrust-tracker/assets/141633147/1c92344b-6f0f-4c94-849d-555fa6245c3d)

The project runs fine with the stable version.

**Comment by mario-nt** [comment]
Someone already opened an issue on this bug on the SQLX package:

- https://github.com/launchbadge/sqlx/issues/3118

**Comment by josecelano** [comment]
Closed via https://github.com/torrust/torrust-tracker/pull/732/commits/45c77c33168dce1e5e8c01e82cde79dfd8842393

**Comment by mario-nt** [comment]
One of the contributors answered telling that dependency change will be out in the next release of config, so we need to wait until the next version.
