### ISSUE TITLE
Use the tracker in a existing environment

### ISSUE THREAD

**Issue by ERR1R** [torrust/torrust-tracker#762]
How would i use this in a existing tracker build in php/angurlarjs? Is it possible to use only the tracker part with php. With some php class or something. Think passkey etc...

**Comment by josecelano** [comment]
> How would i use this in a existing tracker build in php/angurlarjs? Is it possible to use only the tracker part with php. With some php class or something. Think passkey etc... 

Hi @ERR1R you can deploy the Tracker independently from the Torrust Index. If you are using another PHP/angularjs Index you can use the Tracker REST API. There is no PHP wrapper for the API but it would be very easy to build. It could also be interesting to implement one for the project if that can help with the integration with others indexes. Is it a popular open-source solution or a custom one?

**Comment by ERR1R** [comment]
Thanks! I'm gonna try it out!  its based on this one:  https://github.com/swetorrentking/rartracker 

if there is some easy php wrapper/class/integration i think more sites would use your tracker.  Of course we have ocelot and xbt but i really want something newer like your project. I would switch my site completely if i knew how to code in rust :-)

for now u miss some things on your index that i really would like to see :D 

Ps. if ya want to look around at my site you can contact me and ill invite you. Email me at fukinballer@gmail.com

**Comment by josecelano** [comment]
> Thanks! I'm gonna try it out! its based on this one: https://github.com/swetorrentking/rartracker
> 
> if there is some easy php wrapper/class/integration i think more sites would use your tracker. Of course we have ocelot and xbt but i really want something newer like your project. I would switch my site completely if i knew how to code in rust :-)
> 
> for now u miss some things on your index that i really would like to see :D
> 
> Ps. if ya want to look around at my site you can contact me and ill invite you. Email me at [fukinballer@gmail.com](mailto:fukinballer@gmail.com)

Hi @ERR1R thank you for your feedback.

[Here](https://github.com/torrust/torrust-tracker/blob/develop/tests/servers/api/v1/client.rs) you can find a Rust wrapper for the API we are using for testing. 

It would be very helpful for us to know which features you miss from our Index. You can open a feature request [here](https://github.com/torrust/torrust-tracker/discussions/categories/feature-requests). Right now we are focused on finishing our next major release (v3.0.0) but afterwards, we want the community to participate in the [roadmap](https://github.com/orgs/torrust/projects/10/views/1).

I will contact you. You know, that's precisely what I'm doing at the moment. I'm researching different trackers and indexes.

WIP

**Indexes**

![image](https://github.com/torrust/torrust-tracker/assets/58816/a4fa0ed2-1d28-4916-8c21-678ca557b6d4)

**Trackers**

![image](https://github.com/torrust/torrust-tracker/assets/58816/377045b7-e53c-4180-be58-722ac8bfc9dd)

I started the table based on [this](https://github.com/HDVinnie/Torrent-Tracker-Platforms/blob/master/README.md) one by @HDVinnie.

I'm going to close this issue and I will open a new FR for a PHP wrapper for the Tracker API.

PS: I used to code in PHP and I liked but you will enjoy Rust too. In the beginning, it can be a little tough but It is worth the effort. On the other hand, only the backend is in Rust. The frontend is Nuxt (VUE).

**Comment by josecelano** [comment]
By the way @ERR1R [UNIT3D](https://github.com/HDInnovations/UNIT3D-Community-Edition) is written in PHP/JS.

**Comment by ERR1R** [comment]
@josecelano  i know..  i installed it couple of years ago and its to bloated for me.. and i do not like the layout at all. 
you'll see what i mean if you browse on my site :)

the biggest problem i have with my site is that the tracker part is in php/mysql (no redis) and it needs allot of resources with all the extra scripts running. i upgraded to a 40 core server with 96 GB RAM and now it seems to work allot better.
So it would be good to switch to another tracker software for the announce and peers etc.. The frontend is doing fine! 

I looked at mika https://github.com/leighmacdonald/mika but i could not get it working.. it looked promising but i guess its not finished.  Angularjs is long dead but i do not have the skills to upgrade the code for that so starting with the tracker only would be good enough for me at this time.   

ps. If your project would have the same features as mine and i could make it look like a bit like i want I would switch in a heartbeat!

**Comment by josecelano** [comment]
> @josecelano i know.. i installed it couple of years ago and its to bloated for me.. and i do not like the layout at all. you'll see what i mean if you browse on my site :)

I'm looking forward to seeing it.

> 
> the biggest problem i have with my site is that the tracker part is in php/mysql (no redis) and it needs allot of resources with all the extra scripts running. i upgraded to a 40 core server with 96 GB RAM and now it seems to work allot better. So it would be good to switch to another tracker software for the announce and peers etc.. The frontend is doing fine!
> 
> I looked at mika https://github.com/leighmacdonald/mika but i could not get it working.. it looked promising but i guess its not finished. Angularjs is long dead but i do not have the skills to upgrade the code for that so starting with the tracker only would be good enough for me at this time.
> 

The Tracker API documentation is [here](https://docs.rs/torrust-tracker/latest/torrust_tracker/servers/apis/v1/index.html). You can check if it is enough for you or maybe you need more endpoints.

> ps. If your project would have the same features as mine and i could make it look like a bit like i want I would switch in a heartbeat!

In the Torrust Index the [backend](https://github.com/torrust/torrust-index) and the [fronted](https://github.com/torrust/torrust-index-gui) and separate projects. That decision was made on purpose to allow users to design their custom interfaces.
