### ISSUE TITLE
qstion

### ISSUE THREAD

**Issue by ERR1R** [torrust/torrust-tracker#771]
I installed the tracker and its running. But its not clear to me why i have to create an auth key because i already use an existing persistent passkey in a mariadb users table.   Can you explain to me how i would do this with an existing passkey?

**Comment by josecelano** [comment]
Hi @ERR1R at the moment the tracker does not support uploading pre-existing keys. You must use the [tracker API](https://docs.rs/torrust-tracker/3.0.0-alpha.11/torrust_tracker/servers/apis/v1/context/auth_key/index.html) to create new keys for the torrust tracker.

Besides, the [Torrust Tracker doesn't support permanent keys either](https://github.com/torrust/torrust-tracker/discussions/244). However, you can set a long expiration date.

Are you using permanent keys?

I guess we could add a new endpoint to upload pre-generated keys. At the moment tracker keys are 32-char strings. What type of keys are you using?

With the current version, you can only generate a new key and change the one you have in your database. Would you be interested in using the previous one? Why? Are you using more than one tracker? You want to be able to switch bak to the previous tracker?

@da2ce7

**Comment by ERR1R** [comment]
well, if we change passkey for users then all seeding torrents for all users are invalid and have to be redownloaded!  :-). 
i don't want to do that!

Yes, 32 characters passkeys

**Comment by josecelano** [comment]
> well, if we change passkey for users then all seeding torrents for all users are invalid and have to be redownloaded! :-).
> 
> i don't want to do that

Thank you @ERR1R for the clarification. It's now clear (and obvious) to me. I'm still relatively new to BitTorrent protocols. I was thinking only about new downloads. Allowing to submit pre-existing keys is a must feature for the tracker to allow people to migrate to the Torrust tracker if they are already in production.

I will open new issues for it.

**Comment by josecelano** [comment]
Relates to: https://github.com/torrust/torrust-tracker/issues/773

**Comment by josecelano** [comment]
This is already a new feature tracker [here](https://github.com/torrust/torrust-tracker/issues/773).

**Comment by josecelano** [comment]
Hi @ERR1R, I've added a new endpoint [here](https://github.com/torrust/torrust-tracker/issues/974) to upload pre-generated keys.
