### ISSUE TITLE
32-bit Unsigned Integer Too Small for Uploaded/Downloaded/Left/Corrupt Values

### ISSUE THREAD

**Issue by PseudoResonance** [torrust/torrust-tracker#8]
With many torrents, a u32 is too small for the uploaded, downloaded, left and corrupt bytes values. 4294967295 is only a 4GiB file...

**Comment by mickvandijke** [comment]
You're absolutely right, I'll change them to u64.

**Comment by mickvandijke** [comment]
https://github.com/torrust/torrust-tracker/commit/007a4219b69ff74ca488c64e49034e22dee27c41
