### ISSUE TITLE
Error building the tracker: `unresolved import std::hash::DefaultHasher`

### ISSUE THREAD

**Issue by BorjaPractica** [torrust/torrust-tracker#877]
![5851DFCC-7788-4701-93E4-25DF8F0E9016](https://github.com/torrust/torrust-tracker/assets/166434338/519ffd6d-8d51-4c4d-9b65-fdbf8d67b145)
If you encounter the same error, please follow these steps: visit the official Rust website, where you will find a command to execute and install Rust. Run this command, and the error should no longer occur.

**Comment by josecelano** [comment]
THank you @BorjaPractica.
