### ISSUE TITLE
DB Drivers

### ISSUE THREAD

**Issue by HDVinnie** [torrust/torrust-tracker#9]
Is MySQL planned? This looks interesting and maybe beneficial for my project here https://github.com/HDInnovations/UNIT3D-Community-Edition

**Comment by mickvandijke** [comment]
Adding support for other DB drivers is something I'm definitely planning to do :)

**Comment by HDVinnie** [comment]
@WarmBeer you on discord by any chance?

**Comment by mickvandijke** [comment]
Yeah, `Warm Beer#3352`

**Comment by mickvandijke** [comment]
This is actively being worked on now 😄

**Comment by mickvandijke** [comment]
https://github.com/torrust/torrust-tracker/commit/5baea30dfe2f9cb2f3005de63775622bf3bb3396

**Comment by mickvandijke** [comment]
Will be merged into main after refactoring some other code.

**Comment by mickvandijke** [comment]
This has been implemented in the released v2.3.0
